"""add image col for category

Revision ID: a4f138918e0f
Revises: 36fd6ed88a68
Create Date: 2023-04-04 01:21:34.403459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f138918e0f'
down_revision = '36fd6ed88a68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
